/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ERC1271 } from "../ERC1271";

export class ERC1271__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1271 {
    return new Contract(address, _abi, signerOrProvider) as ERC1271;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "permissionHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
