/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { OwnableByERC721 } from "../OwnableByERC721";

export class OwnableByERC721__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<OwnableByERC721> {
    return super.deploy(overrides || {}) as Promise<OwnableByERC721>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OwnableByERC721 {
    return super.attach(address) as OwnableByERC721;
  }
  connect(signer: Signer): OwnableByERC721__factory {
    return super.connect(signer) as OwnableByERC721__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableByERC721 {
    return new Contract(address, _abi, signerOrProvider) as OwnableByERC721;
  }
}

const _abi = [
  {
    inputs: [],
    name: "nft",
    outputs: [
      {
        internalType: "address",
        name: "nftAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "ownerAddress",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610169806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806347ccca021461003b5780638da5cb5b1461006c575b600080fd5b610043610074565b6040805173ffffffffffffffffffffffffffffffffffffffff9092168252519081900360200190f35b610043610090565b60005473ffffffffffffffffffffffffffffffffffffffff1690565b60008054604080517f6352211e000000000000000000000000000000000000000000000000000000008152306004820152905173ffffffffffffffffffffffffffffffffffffffff90921691636352211e91602480820192602092909190829003018186803b15801561010257600080fd5b505afa158015610116573d6000803e3d6000fd5b505050506040513d602081101561012c57600080fd5b505190509056fea2646970667358221220b46103eb73bee6ee91ef26ce63a7045e064e0c491ba66a32304773230d17903364736f6c63430007060033";
